add fixes to circle2d: line_intersections
Dessia-tech/volmdlr pull request #1048
Opened 2023-09-12 17:44 UTC by WirajanDASILVA

* **Please check if the PR fulfills these requirements**
- [X] The commit messages follows our guidelines (explicit, in english)
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)
- [X] CHANGELOG.md has been updated

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bug fix:
- [ ] New features:
- [ ] Documentation
- [ ] Optimization

* **Other information**:

2023-09-12 17:59 UTC, WirajanDASILVA commented on volmdlr/curves.py
> +            return [self.center + self.radius * direction_vector, self.center - self.radius * direction_vecto
```suggestion
            return [self.center + self.radius * direction_vector, self.center - self.radius * direction_vector]
```

2023-10-02 10:39 UTC, GabrielJMS requested changes

2023-10-02 10:39 UTC, GabrielJMS commented on .pyenchant_dessia.dict
> +cylindricalface
Respect the alphabetical order from A to Z

2023-10-02 12:21 UTC, GabrielJMS approved these changes

2023-10-02 13:04 UTC, merged