add cut by plane method
Dessia-tech/volmdlr pull request #131
Opened 2021-03-16 22:37 UTC by DumouchelP

* **Please check if the PR fulfills these requirements**
- [ ] The commit messages follows our guidelines (explicit, in english)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] CHANGELOG.md has been updated

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bug fix:
- [x] New features:
- [ ] Documentation
- [ ] Optimization

* **Other information**:

2021-03-17 14:04 UTC, masfaraud requested changes

2021-03-17 14:04 UTC, masfaraud commented on volmdlr/templates.py
> +      scene.debugLayer.show();
Comment by default

2021-03-17 14:04 UTC, masfaraud commented on volmdlr/edges.py
> +    def straight_line_area(self):
Remove, already implemeted on dev

2021-03-22 11:26 UTC, DumouchelP reviewed
Ok for the changes

2021-03-24 18:24 UTC, merged