arc_to_nurbs function
Dessia-tech/volmdlr pull request #1341
Opened 2024-03-28 01:38 UTC by jvictornreis

* **Please check if the PR fulfills these requirements**
- [x] The commit messages follows our guidelines (explicit, in english)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [x] CHANGELOG.md has been updated

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bug fix:
- [x] New features:
- [ ] Documentation
- [ ] Optimization

* **Other information**:
Was added a new function to return the necessary parameters to create a NURBS curve equivalent to a given arc

2024-03-28 10:35 UTC, GabrielJMS requested changes

2024-03-28 10:35 UTC, GabrielJMS commented on volmdlr/edges.py
> +        elif arc.angle <= (3 * 2) * math.pi:
```suggestion
        elif arc.angle <= 1.5 * math.pi:
```

2024-03-28 10:35 UTC, GabrielJMS commented on volmdlr/edges.py
> +        weights.insert(0, 1.)
```suggestion
        control_points = [arc.start]
        weights = [1.0]
        knots = [0.0]
        knot_multiplicities = [3]
```

2024-03-28 10:35 UTC, GabrielJMS commented on volmdlr/edges.py
> +        weights.insert(0, 1.)
You can simplify this block by creating the lists directly with the values

2024-03-28 10:35 UTC, GabrielJMS commented on volmdlr/edges.py
> +            vector_end = (common_control_point - arc.center).to_vector()
Normally, points subtraction should return a vector, so you don't need to convert it into a vector. Can you verify that, please?

2024-03-28 10:35 UTC, GabrielJMS commented on tests/edges/test_bsplinecurve.py
> +        expected_knots = [0.0, 0.3333333333333333, 0.6666666666666666, 1.0, 1.0]
To be in line with our definition, it is expected that nodes do not have repeating values. For this case, I think it should be rewritten like this:
       expected_knots = [0.0, 0.3333333333333333, 0.6666666666666666, 1.0]
       expected_knot_multiplicities = [3, 2, 2, 5]
 
 The resulting knot-vector would be U = [0.0, 0.0, 0.0, 0.333, 0.333, 0.6666, 0.6666, 1.0, 1.0, 1.0, 1.0, 1.0]
 
 Verify that this is as expected by the algorithm. By the definition the size of the knot vector should be equal to: len(control_points) + degree + 1. As you have 7 control_points, and I imagine the degree is 2, we should expect a knot vector of size 10. So I think maybe the knot 1.0, with multiplicity 2 should not exist for this case? Can you validate this please?
       
![image](https://github.com/Dessia-tech/volmdlr/assets/89979482/2da52b40-0504-4669-aa5b-d28f4b82ad59)
![image](https://github.com/Dessia-tech/volmdlr/assets/89979482/418efb24-f27f-41b0-82c4-cb9a02c01bba)

2024-03-29 15:12 UTC, jvictornreis commented on volmdlr/edges.py
> +            vector_end = (common_control_point - arc.center).to_vector()
I tried it, but didn't work 
![WhatsApp Image 2024-03-29 at 12 11 14](https://github.com/Dessia-tech/volmdlr/assets/65500341/da4b0357-71e3-46d7-b21d-ba0bc1319049)

2024-04-03 09:21 UTC, GabrielJMS approved these changes

2024-04-03 10:30 UTC, merged