[WIP] Bspline: 3d_to_2d with dimension
Dessia-tech/volmdlr pull request #261
Opened 2021-12-29 16:30 UTC by sbendjebla

* **Please check if the PR fulfills these requirements**
- [ ] The commit messages follows our guidelines (explicit, in english)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] CHANGELOG.md has been updated

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [x] Bug fix:
- [ ] New features:
- [ ] Documentation
- [ ] Optimization

* **Other information**:
 _I improved the methods for **3d_to_2d_with_dimension**, and **2d_with_dimension_to_3d** (for edges: linesegment, bsplinecurve, arc/ wires/ contours)._
_I improved **arc3d_to_2d**: the result is now a **bsplinecurve2d** instead of a list of linesegment2d_
_I added **arc2d_to_3d**: the result is a **bsplinecurve3d**_

2022-02-14 18:26 UTC, AxelRinghausen commented on volmdlr/faces.py
> +            [points_x, points_y, xmin, xmax, ymin, ymax] = key
You are overwriting points_x, points_y, xmin, xmax, ymin, ymax each time you iterate on the loop. So it turns out to be equal to `[points_x, points_y, xmin, xmax, ymin, ymax] = self._grids2d[-1]`

2022-02-14 18:36 UTC, AxelRinghausen commented on volmdlr/faces.py
> +            [points_x, points_y, xmin, xmax, ymin, ymax] = key
Same comment.

2022-02-14 18:39 UTC, AxelRinghausen commented on volmdlr/faces.py
> +        return arc2d_with_dimension
Are you sure an Arc2D in parametric coordinates is also an Arc2D in dimensional coordinates ?

2022-02-14 18:41 UTC, AxelRinghausen commented on volmdlr/faces.py
> +        return arc2d
The other way around now : are you sure an Arc2D in dimensional coordinates is also an Arc2D in parametric coordinates ?

2022-02-14 18:47 UTC, AxelRinghausen commented on volmdlr/faces.py
> +            points_y = key[1]
Same comment here about self._grids2d.

2022-02-15 08:22 UTC, sbendjebla commented on volmdlr/faces.py
> +                    points, max(self.degree_u, self.degree_v))
It's done !

2022-02-18 15:20 UTC, AxelRinghausen requested changes

2022-02-18 16:00 UTC, sbendjebla commented on volmdlr/faces.py
> +        return arc2d
It's done !

2022-02-18 16:45 UTC, AxelRinghausen approved these changes

2022-02-18 17:03 UTC, merged