Include python Stream in Step module
Dessia-tech/volmdlr pull request #264
Opened 2022-01-03 22:33 UTC by DumouchelP

* **Please check if the PR fulfills these requirements**
- [x] The commit messages follows our guidelines (explicit, in english)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] CHANGELOG.md has been updated

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bug fix:
- [x] New features:
- [ ] Documentation
- [ ] Optimization

* **Other information**:

2022-01-04 10:37 UTC, AxelRinghausen submitted a review, later dismissed

2022-01-11 09:38 UTC, masfaraud requested changes
Create a separate method for stream

2022-01-17 13:44 UTC, masfaraud requested changes

2022-01-17 13:44 UTC, masfaraud commented on volmdlr/step.py
> +    def __init__(self, stepfile: str = None, stream: BinaryIO = None):
Weird to have double args in init. I suggest init with lines (list[str]) and have classmethods to read from stream and from file

2022-01-17 13:44 UTC, masfaraud commented on volmdlr/step.py
> +    def read_stream(self):
have stream in param not in self

2022-01-24 21:56 UTC, DumouchelP reviewed
2 new class_method to instantiate Step

2022-01-31 18:43 UTC, masfaraud commented
Embeded in another PR

2022-01-31 18:43 UTC, closed without merging