feat: Take inner contours into account
Dessia-tech/volmdlr pull request #284
Opened 2022-01-19 16:36 UTC by AxelRinghausen

* **Please check if the PR fulfills these requirements**
- [x] The commit messages follows our guidelines (explicit, in english)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] CHANGELOG.md has been updated

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bug fix:
- [ ] New features:
- [ ] Documentation
- [ ] Optimization

* **Other information**:

2022-11-03 17:16 UTC, WirajanDASILVA requested changes

2022-11-09 11:28 UTC, AxelRinghausen commented on volmdlr/edges.py
> +        return [self.point_at_abscissa(i * length / n) for i in range(n + 1)]
Yes indeed !

2022-11-16 12:46 UTC, WirajanDASILVA submitted a review, later dismissed

2022-11-16 12:46 UTC, WirajanDASILVA commented on volmdlr/faces.py
> +        points = [self.control_points[0], self.control_points[math.ceil(len(self.control_points) / 2)],
add docstring

2022-11-16 12:53 UTC, WirajanDASILVA approved these changes

2022-11-17 08:27 UTC, merged