Updatedistancescript
Dessia-tech/volmdlr pull request #314
Opened 2022-02-03 16:55 UTC by MackJoly

* **Please check if the PR fulfills these requirements**
- [X] The commit messages follows our guidelines (explicit, in english)
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] CHANGELOG.md has been updated

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [X] Bug fix: update all distance script
- [ ] New features:
- [ ] Documentation
- [ ] Optimization

* **Other information**:

2022-02-04 17:32 UTC, AxelRinghausen requested changes

2022-02-04 18:36 UTC, MackJoly commented on scripts/read_steps.py
> +step = volmdlr.step.Step('C:\\Users\\Mack\\Downloads\\boite de vitesse DB45 HR18DD.stp')
Thank you, i forgot it. It was a personal usecase

2022-02-10 17:46 UTC, AxelRinghausen submitted a review, later dismissed

2022-03-17 13:56 UTC, AxelRinghausen approved these changes

2022-05-10 14:53 UTC, sbendjebla commented
@MackJoly is this PR still useful ?

2022-05-10 14:55 UTC, MackJoly commented
> @MackJoly is this PR still useful ?

Yes, it is an update of distance script used by drone

2022-05-10 15:09 UTC, sbendjebla commented
@MackJoly  So, can you resolve conflicts, please ?

2022-06-28 16:17 UTC, AxelRinghausen approved these changes

2022-09-27 15:50 UTC, sbendjebla commented
@MackJoly This PR needs to be merged or not ?

2022-09-27 15:52 UTC, MackJoly commented
It could, it is an evolution of script distance that were incorrect, it needs to be checked i think

2023-07-07 15:47 UTC, closed without merging