Contour2D/3D: eq (2)
Dessia-tech/volmdlr pull request #343
Opened 2022-03-21 15:25 UTC by sbendjebla

* **Please check if the PR fulfills these requirements**
- [ ] The commit messages follows our guidelines (explicit, in english)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] CHANGELOG.md has been updated

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [x] Bug fix:
- [ ] New features:
- [ ] Documentation
- [ ] Optimization

* **Other information**:

It's the same version for **2D** & **3D**, maybe, we can put it in **Contour** ?!

2022-03-22 15:56 UTC, AxelRinghausen requested changes

2022-03-22 15:56 UTC, AxelRinghausen commented on volmdlr/wires.py
> +        return False
Just a small optimization.
```suggestion
    def __eq__(self, other_):
        if other_.__class__.__name__ != self.__class__.__name__:
            return False
        if len(self.primitives) != len(other_.primitives):
            return False
        equal = 0
        for prim1 in self.primitives:
            reverse1 = prim1.reverse()
            found = False
            for prim2 in other_.primitives:
                reverse2 = prim2.reverse()
                if (prim1 == prim2 or reverse1 == prim2
                        or reverse2 == prim1 or reverse1 == reverse2):
                    equal += 1
                    found = True
            if not found:
                return False
        if equal == len(self.primitives):
            return True
        return False
```

2022-03-22 15:56 UTC, AxelRinghausen commented on volmdlr/wires.py
> +        return False
Small optimization.
```suggestion
        equal = 0
        for prim1 in self.primitives:
            reverse1 = prim1.reverse()
            found = False
            for prim2 in other_.primitives:
                reverse2 = prim2.reverse()
                if (prim1 == prim2 or reverse1 == prim2
                        or reverse2 == prim1 or reverse1 == reverse2):
                    equal += 1
                    found = True
            if not found:
                return False
        if equal == len(self.primitives):
            return True
        return False
```

2022-03-24 15:34 UTC, sbendjebla commented on volmdlr/wires.py
> +        return False
Thanks !

2022-03-24 15:34 UTC, sbendjebla commented on volmdlr/wires.py
> +        return False
Thanks !

2022-03-29 08:28 UTC, merged