Fix step: version of frame_mapping
Dessia-tech/volmdlr pull request #417
Opened 2022-06-24 13:54 UTC by WirajanDASILVA

* **Please check if the PR fulfills these requirements**
- [X] The commit messages follows our guidelines (explicit, in english)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] CHANGELOG.md has been updated

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [X] Bug fix:
- [ ] New features:
- [ ] Documentation
- [ ] Optimization

* **Other information**:

2022-06-24 14:48 UTC, AxelRinghausen requested changes
Use either frame_mapping_in_place, or store the new shell3d in a variable.

2022-06-24 14:53 UTC, WirajanDASILVA commented
> Use either frame_mapping_in_place, or store the new shell3d in a variable.

ahh, thank you, Axel!! I'll fix it

2022-06-24 15:33 UTC, AxelRinghausen approved these changes

2022-06-24 15:44 UTC, AxelRinghausen commented
To be merge after https://github.com/Dessia-tech/volmdlr/pull/369

2022-06-27 07:41 UTC, sbendjebla approved these changes

2022-06-28 14:39 UTC, merged