fix copy in Circle2D.discretise
Dessia-tech/volmdlr pull request #420
Opened 2022-06-28 14:38 UTC by pgibertini

* **Please check if the PR fulfills these requirements**
- [ ] The commit messages follows our guidelines (explicit, in english)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] CHANGELOG.md has been updated

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [x] Bug fix: old "copy" parameter was used in Circle2D.discretise method
- [ ] New features:
- [ ] Documentation
- [ ] Optimization

* **Other information**:

2022-06-28 15:47 UTC, masfaraud submitted a review, later dismissed

2022-06-28 16:31 UTC, AxelRinghausen requested changes

2022-06-28 16:31 UTC, AxelRinghausen commented on volmdlr/wires.py
>          return points
This is now a deprecated method. If you pull dev you will have access to `discretization_points`, the new way of naming all discretization methods.

2022-07-05 08:07 UTC, AxelRinghausen approved these changes

2022-07-05 08:08 UTC, merged