Block center
Dessia-tech/volmdlr pull request #439
Opened 2022-08-30 12:40 UTC by MackJoly

* **Please check if the PR fulfills these requirements**
- [X] The commit messages follows our guidelines (explicit, in english)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [X] CHANGELOG.md has been updated

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bug fix:
- [X] New features: primitives3d.Block.center_faces
- [ ] Documentation
- [ ] Optimization

* **Other information**:

2022-10-18 14:32 UTC, masfaraud requested changes

2022-10-18 14:32 UTC, masfaraud commented on volmdlr/faces.py
> -        self_set = set([self.point1, self.point2, self.point3])
would use https://www.pythontutorial.net/python-basics/python-disjoint-sets/

2022-10-18 14:32 UTC, masfaraud commented on volmdlr/primitives3d.py
> +    def center_faces(self):
rename to faces_center (more english)

2022-11-02 11:26 UTC, masfaraud approved these changes

2022-11-02 14:19 UTC, sbendjebla approved these changes

2022-11-02 15:02 UTC, merged