add step files to read with volmdlr
Dessia-tech/volmdlr pull request #456
Opened 2022-09-25 21:15 UTC by younesdessia

* **Please check if the PR fulfills these requirements**
- [X ] The commit messages follows our guidelines (explicit, in english)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)
- [ ] CHANGELOG.md has been updated

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bug fix:
- [ ] New features:
- [X] Documentation
- [ ] Optimization

* **Other information**:

2022-12-02 11:20 UTC, AxelRinghausen requested changes

2022-12-02 11:20 UTC, AxelRinghausen commented on volmdlr/step.py
> +    name = 'B_SPLINE_CURVE'
Comment the name if it is not used.

2022-12-02 11:20 UTC, AxelRinghausen commented on volmdlr/step.py
> +    name = 'B_SPLINE_SURFACE'
Comment the name if it is not used.

2023-01-03 15:38 UTC, masfaraud commented
Closing as it is handled by devs

2023-01-03 15:38 UTC, closed without merging