Fix: Contour2d.cut_by_wire
Dessia-tech/volmdlr pull request #497
Opened 2022-10-18 08:48 UTC by sbendjebla

* **Please check if the PR fulfills these requirements**
- [ ] The commit messages follows our guidelines (explicit, in english)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] CHANGELOG.md has been updated

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bug fix:
- [ ] New features:
- [ ] Documentation
- [ ] Optimization

* **Other information**:
To be merged after #496

2022-10-25 20:37 UTC, WirajanDASILVA requested changes

2022-10-25 20:37 UTC, WirajanDASILVA commented on volmdlr/wires.py
> +                        break
```suggestion
            for point in points_intersections:
                if point not in [point1, point2] and Wire2D(closing_wire).point_over_wire(point):
                    closing_wire = wire.extract_without_primitives(point1, point2, False)
                    break
```

2022-10-27 09:37 UTC, sbendjebla commented on volmdlr/wires.py
> +                        break
Done !

2022-10-27 11:10 UTC, WirajanDASILVA approved these changes

2022-10-31 08:25 UTC, merged