502 circle2d cut by line
Dessia-tech/volmdlr pull request #503
Opened 2022-10-21 13:20 UTC by GabrielJMS

* **Please check if the PR fulfills these requirements**
- [ ] The commit messages follows our guidelines (explicit, in english)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] CHANGELOG.md has been updated

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bug fix:
- [ ] New features:
- [ ] Documentation
- [ ] Optimization

* **Other information**:

2022-10-25 20:31 UTC, WirajanDASILVA requested changes

2022-10-25 20:31 UTC, WirajanDASILVA commented on tests/wires/test_circle2d.py
> +    def test_split_by_line(self):
`list_arcs` should one inside `test_spline_by_line`, I'd say

2022-11-03 08:23 UTC, masfaraud submitted a review, later dismissed

2022-11-07 11:50 UTC, WirajanDASILVA approved these changes

2022-11-07 11:50 UTC, merged