Step to volmdlr: Arc3D from stem to volmdlr for Cylindrical and Toroidal Surface
Dessia-tech/volmdlr pull request #521
Opened 2022-11-04 16:38 UTC by GabrielJMS

* **Please check if the PR fulfills these requirements**
- [ ] The commit messages follows our guidelines (explicit, in english)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] CHANGELOG.md has been updated

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [x ] Bug fix:
- [ ] New features:
- [ ] Documentation
- [ ] Optimization

* **Other information**:

2022-11-29 15:38 UTC, masfaraud requested changes

2022-11-29 15:38 UTC, masfaraud commented on scripts/step/read_steps.py
> -    'cone2.step',
Put back simple steps tests?

2022-11-29 15:38 UTC, masfaraud commented on volmdlr/faces.py
> +                if isinstance(self, SphericalSurface3D):
I hate this pattern if isinstance: can we switch to a method that each concept would implement

2022-12-08 10:29 UTC, WirajanDASILVA commented on volmdlr/faces.py
> +        #     periodic=bspline_curve3d.periodic)]
clean?

2022-12-08 10:29 UTC, WirajanDASILVA commented on volmdlr/faces.py
> +        #     end = start - volmdlr.Point2D(arc3d.angle, 0)
clean?

2022-12-08 10:31 UTC, WirajanDASILVA commented on volmdlr/faces.py
> +            #                      - prim.end.y)
clean?

2022-12-23 16:54 UTC, GabrielJMS commented
Closing because this PR is outdated and a new one has replaced it

2022-12-23 16:54 UTC, closed without merging