Triangle3D performance
Dessia-tech/volmdlr pull request #646
Opened 2023-01-27 14:19 UTC by masfaraud

* **Please check if the PR fulfills these requirements**
- [ ] The commit messages follows our guidelines (explicit, in english)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [x] CHANGELOG.md has been updated

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [x] Optimization: Avoid calling base dict of dessia object

* **Other information**:

2023-02-01 11:29 UTC, masfaraud commented on volmdlr/edges.py
> +            I = volmdlr.Vector2D(point[0], point.y)
.x

2023-02-03 14:26 UTC, WirajanDASILVA approved these changes

2023-02-03 14:52 UTC, WirajanDASILVA requested changes

2023-02-03 14:52 UTC, WirajanDASILVA commented on volmdlr/edges.py
> +    #         name, x1, y1, z1, x2, y2, z2)
Is this still important, if not could you please delete it?

2023-02-03 14:52 UTC, WirajanDASILVA commented on volmdlr/edges.py
> +    #                                                                    False)
delete it?

2023-02-03 14:52 UTC, WirajanDASILVA commented on volmdlr/edges.py
> +    #         .format(name, xs, ys, zs, xi, yi, zi, xe, ye, ze)
delete it?

2023-02-03 14:52 UTC, WirajanDASILVA commented on volmdlr/edges.py
> +    #         name, xs, ys, zs, xi, yi, zi, xe, ye, ze)
delete it?

2023-02-03 16:08 UTC, masfaraud commented on volmdlr/edges.py
> +    #         name, xs, ys, zs, xi, yi, zi, xe, ye, ze)
done

2023-02-04 11:04 UTC, WirajanDASILVA approved these changes

2023-02-08 12:32 UTC, merged