Step reader - handling inconsistencies from step files
Dessia-tech/volmdlr pull request #689
Opened 2023-02-23 13:53 UTC by GabrielJMS

* **Please check if the PR fulfills these requirements**
- [x] The commit messages follows our guidelines (explicit, in english)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] CHANGELOG.md has been updated

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bug fix:
- [x] New features:
- [ ] Documentation
- [ ] Optimization

* **Other information**:

![image](https://user-images.githubusercontent.com/89979482/220925295-02d9726c-6528-4689-ac8e-105586d8a176.png)
![image](https://user-images.githubusercontent.com/89979482/220925843-e0c2fda8-396d-4292-8ac7-828335067001.png)
![image](https://user-images.githubusercontent.com/89979482/220926182-ce721805-5b2b-4460-933d-b900258fa4e7.png)
![image](https://user-images.githubusercontent.com/89979482/220926473-c64f21a2-0c24-4368-98be-d66a7c2bd727.png)
![image](https://user-images.githubusercontent.com/89979482/220926708-43b943b7-e65b-4827-8d0f-37077a801ef9.png)
![image](https://user-images.githubusercontent.com/89979482/220926913-995a6049-2176-47e5-8bd9-15023a622471.png)
![image](https://user-images.githubusercontent.com/89979482/220927153-2af15b9a-4491-4ffa-8a7e-8aaec8a396e9.png)

2023-02-24 16:33 UTC, WirajanDASILVA commented on volmdlr/faces.py
> +        if start != end:
```suggestion
        if not start.is_close(end):
```

2023-02-28 11:09 UTC, WirajanDASILVA approved these changes

2023-03-01 13:49 UTC, masfaraud requested changes

2023-03-01 13:49 UTC, masfaraud commented on volmdlr/faces.py
> +        x, y, z = self.frame.global_to_local_coordinates(point3d)
is z used? _ was there to avoid unused variable pylint error

2023-03-01 13:49 UTC, masfaraud commented on volmdlr/step.py
> +    def instanciate(self, name, arguments, object_dict, step_id):
I changed on dev instanciate to instantiate (correct the typo). Suggest to rename to instantiate

2023-03-01 13:49 UTC, masfaraud commented on volmdlr/step.py
> -                        volmdlr_object = self.instantiate(
instantiate

2023-03-01 13:49 UTC, masfaraud commented on volmdlr/step.py
> +                # INSTANCIATION
typo

2023-03-03 16:44 UTC, masfaraud approved these changes

2023-03-03 16:45 UTC, merged